name: DeployDoc

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Packages
        working-directory: ./Scripter.NpmPackage
        run: npm install
      - name: Build
        working-directory: ./Scripter.NpmPackage
        run: npm run doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./Scripter.NpmPackage/doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1